name: Continous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'cmnemoi_learn/**'
      - 'tests/**'

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
        cache: 'pip'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run Black
      run: python -m black --check .
    - name: Run Mypy
      run: python -m mypy .
    - name: Run Pylint
      run: python -m pylint cmnemoi_learn tests

  test:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
        cache: 'pip'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run unit tests
      run: python -m pytest --cov=cmnemoi_learn/
    - name: Upload coverage to Coveralls
      uses: coverallsapp/github-action@v2
      with:
        format: python
        github-token: ${{ secrets.GITHUB_TOKEN }}