name: Continous Delivery

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release:
    name: Create Github Release
    runs-on: ubuntu-22.04
    concurrency: release
    permissions:
      id-token: write
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.ADMINISTRATOR_GITHUB_TOKEN }}

    - name: Create release
      uses: python-semantic-release/python-semantic-release@master
      with:
        git_committer_name: ${{ secrets.NERON_GITHUB_NAME }}
        git_committer_email: ${{ secrets.NERON_GITHUB_EMAIL }}
        github_token: ${{ secrets.ADMINISTRATOR_GITHUB_TOKEN }}
